### ISSUE TITLE
How to generate payload?

### ISSUE THREAD

**Issue by dereknex** [emqtt/emq-auth-jwt#39]
I cannot find any clear information about generate payload. anyone can't tell me?

**Comment by dereknex** [comment]
I try as below:
header:
```json
{"typ":"JWT","alg":"HS256"}
```
payload:

```json
{
"client_id":"test",
"username": "test"
}
```

But it doesn't work.

**Comment by terry-xiaoyu** [comment]
Do you want to generating a JWT? This plugin only verifies the JWT you passed.

**Comment by dereknex** [comment]
OK, I got it. Thank you.
