### ISSUE TITLE
JWT not passing check

### ISSUE THREAD

**Issue by dreamcatcha** [emqtt/emq-auth-jwt#7]
I have a nodejs app that creates JWT tokens for users and it uses the default alg HS256, and I have set the secret on the node app and the emqtt plugin to be the same but I keep getting the 'password_error' in the logs. What am I doing wrong?

I'm using the paho android client and I put the JWT in the password field

EDIT:

I have found this inner case statement to be throwing the error. What i don't understand is it is decoding fine, but its being encoded a second time? 
```
case jwt:encode(Jwt#jwt.alg, jsx:decode(Jwt#jwt.body), Secret) of
    {ok, Password} -> ok;
    _              -> {error, password_error}
end;
```

**Comment by emqplus** [comment]
@turtleDeng pls check this issue.

**Comment by turtleDeng** [comment]
@dreamcatcha 

Will the body encoded into json, in the coding problem?
https://github.com/emqtt/emq-auth-jwt#example

**Comment by dreamcatcha** [comment]
Not sure exactly what you mean but here is the json header and payload
```
{
  "alg": "HS256",
  "typ": "JWT"
}

{
  "id": "1",
  "screen_name": "MyUsername",
  "iat": 1500623760,
  "iss": "api.example.com",
  "jti": "07381558-b400-411b-8edc-06b1314f262e"
}

// signature omitted and domain changed
```
It looks to me it might be in the looking for body in the above case statement, I'm not an erlang programer so I'm not sure

**Comment by turtleDeng** [comment]
@dreamcatcha  I will add log to print.

**Comment by dreamcatcha** [comment]
@turtleDeng What would i need to modify to see the error, i can change the plugin and rebuild to test, to find the error
